GET http://localhost:4000/api/apps

###
GET http://localhost:4000/api/v1/apps/1

###
GET http://localhost:4000/api/v1/auth/register

###
POST http://localhost:4000/api/v1/auth/login
content-type: application/json

{
    "username": "vernandaspw",
    "password": "Merpati341"
}